name: Setup
description: Setup
runs:
  using: "composite"
  steps:
    - name: Install tools
      run: |
        yum update -y \
        && yum install -y \
            git-2.40.1-1.amzn2.0.3 \
            unzip-6.0-57.amzn2.0.1 \
            yum-utils-1.1.31-46.amzn2.0.1
      shell: sh
    - name: Install Packer
      run: |
        yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo \
        && yum install -y packer-1.11.2-1 \
        && rm -rf /var/cache/yum/* \
        && yum clean all \
        && rm /usr/sbin/packer
      shell: sh
    - name: Install awscli
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
        && unzip awscliv2.zip \
        && ./aws/install
      shell: sh
