name: Setup
description: Setup
runs:
  using: "composite"
  steps:
    - name: Install tools
      run: |
        dnf install -y \
          git \
          unzip \
          sudo \
          dnf-utils
      shell: sh
    - name: Install Packer
      run: |
        dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo \
        && dnf install -y packer-1.11.2-1 \
        && rm -rf /var/cache/dnf/* \
        && dnf clean all
      shell: sh
    - name: Install awscli
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
        && unzip awscliv2.zip \
        && ./aws/install
      shell: sh
