name: Build grpc-sample

on:
  workflow_dispatch:
    inputs:
      app_ver:
        type: string
        required: true
        description: grpc-sample-${app_ver}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2023.1.20230809.0
    steps:
      - name: Preprocess for checkout
        run: dnf install -y tar gzip
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Checkout to artifact-storage
        uses: actions/checkout@v4
        with:
          repository: takahiroaoki/artifact-storage.git
          path: artifact-storage
          ref: main
      - name: Move artifact to the expected directory
        run: mv -n artifact-storage/grpc-sample/grpc-sample-${{ github.event.inputs.app_ver }} projects/grpc-sample/resources
      - name: Build
        working-directory: projects/grpc-sample
        run: |
          packer init .
          packer build -var app_ver=${{ github.event.inputs.app_ver }} .
