name: Build minikube-aws

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        working-directory: projects/minikube-aws
        run: |
          packer init .
          packer build -var-file=variables.pkrvars.hcl .
