name: Build minikube-aws

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2
    steps:
      - name: Preprocess for checkout
        run: |
          curl -sL https://rpm.nodesource.com/setup_16.x | bash -
          yum install -y nodejs
          node -v
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Build
        working-directory: projects/minikube-aws
        run: |
          packer init .
          packer build -var-file=variables.pkrvars.hcl .
